general {
    lock_cmd = pidof hyprlock || hyprlock
    before_sleep_cmd = loginctl lock-session
    after_sleep_cmd = hyprctl dispatch dpms on
}

# 1. Kunci layar setelah 5 menit (300 detik)
listener {
    timeout = 120
    on-timeout = loginctl lock-session
}

# 2. Matikan monitor setelah 5.5 menit (330 detik)
listener {
    timeout = 150
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
}

# 3. Suspend PC setelah 15 menit (900 detik) - Opsional, silakan di-comment jika PC selalu hidup
listener {
    timeout = 150
    on-timeout = systemctl suspend
}
